"""add price column

Revision ID: 6a2767a2f2a8
Revises: 3caac7fc7f8c
Create Date: 2026-04-07 18:49:39.221249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2767a2f2a8'
down_revision: Union[str, Sequence[str], None] = '3caac7fc7f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'price')
    # ### end Alembic commands ###
